/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consolewarriors.Client.View;

import Weapons.Weapon;
import consolewarriors.Common.CharacterType;
import consolewarriors.Common.Shared.Warrior;
import consolewarriors.Common.Shared.WarriorWeapon;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import Characters.Character;
import consolewarriors.Client.Control.GameWindowController;
import consolewarriors.Client.Model.PlayerClient;

/**
 *
 * @author rshum
 */
public class CreationWindow extends javax.swing.JFrame {
    
    private String username = "";
    private ArrayList<Weapon> createdWeapons;
    private ArrayList<Character> createdWarriors;
    
    private String lastImageUsedPath = ""; // Space for improvement.
    
    public CreationWindow() {
        initComponents();
        setUpGUI();
        
        createdWeapons = new ArrayList<>();
        createdWarriors = new ArrayList<>();
        
        displayRegistrationPane();
    }
    
    public void displayRegistrationPane(){
        username = JOptionPane.showInputDialog(this, "Enter your username");
        this.setTitle(username + "'s" + " session");
    }

    public void setUpGUI(){
        this.setResizable(false);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(CreationWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public ImageIcon resizeImage(Image image){
        Image newImage = image.getScaledInstance(lblWarriorImage.getWidth(), lblWarriorImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon resizedImage = new ImageIcon(newImage);
        return resizedImage;
    }
    
    public void addWeapon(Weapon weapon){
        // Add the weapon to the arraylist of the created weapons
        createdWeapons.add(weapon);
        WarriorWeapon currentWeapon = (WarriorWeapon) weapon;
        
        DefaultTableModel tableModel = (DefaultTableModel) tblWeapons.getModel();
        Object[] weaponData = new Object[11];
        
        weaponData[0] = currentWeapon.getName();
        CharacterType[] types = CharacterType.values();
        for (int i = 0; i < currentWeapon.getAttackValueMatrix().size(); i++) {
            weaponData[i + 1] = currentWeapon.getAttackValueMatrix().get(types[i]);
        }

        tableModel.addRow(weaponData);
    }
    
    public void addWarrior(Character warrior) {
        // Add the warrior to the created warriors
       createdWarriors.add(warrior);
        
        Warrior currentWarrior = (Warrior) warrior;

        DefaultTableModel tableModel = (DefaultTableModel) tblWarriors.getModel();
        Object[] warriorData = new Object[7];
        warriorData[0] = currentWarrior.getName();
        warriorData[1] = currentWarrior.getType().stringRepresentationOfCharacterType();

        tableModel.addRow(warriorData);
    }
    
    public void addWeaponToWarrior(Character warrior, int warriorPosition, Weapon weapon){
        Warrior currentWarrior = (Warrior)warrior;
        WarriorWeapon currentWeapon = (WarriorWeapon)weapon;
        currentWarrior.addWeapon(weapon);
        
        int weaponNumber = currentWarrior.getWeapons().size();
        
        tblWarriors.setValueAt(currentWeapon.getName(), warriorPosition, weaponNumber + 1);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWeapons = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfWeaponName = new javax.swing.JTextField();
        btnCreateWeapon = new javax.swing.JButton();
        txfWarriorName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWarriors = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnLoadImage = new javax.swing.JButton();
        cmbxWarriorType = new javax.swing.JComboBox<>();
        lblWarriorImage = new javax.swing.JLabel();
        btnCreateWarrior = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnAssignWeapon = new javax.swing.JButton();
        btnReady = new javax.swing.JButton();
        btnClearWeapons = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        tblWeapons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Fire", "Air", "Water", "White magic", "Black magic", "Electricity", "Ice", "Acid", "Spirituality", "Iron"
            }
        ));
        jScrollPane1.setViewportView(tblWeapons);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel1.setText("Weapons");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Warriors");

        btnCreateWeapon.setText("Create weapon");
        btnCreateWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWeaponActionPerformed(evt);
            }
        });

        txfWarriorName.setToolTipText("Warrior name\n");

        tblWarriors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Weapon 1", "Weapon 2", "Weapon 3", "Weapon 4", "Weapon 5"
            }
        ));
        jScrollPane2.setViewportView(tblWarriors);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel3.setText("Weapon creation");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setText("Warrrior creation");

        btnLoadImage.setText("Select image");
        btnLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadImageActionPerformed(evt);
            }
        });

        cmbxWarriorType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fire", "Air", "Water", "White magic", "Black magic", "Electricity", "Ice", "Acid", "Spirituality", "Iron", " " }));

        lblWarriorImage.setBackground(new java.awt.Color(255, 255, 255));
        lblWarriorImage.setBorder(new javax.swing.border.MatteBorder(null));
        lblWarriorImage.setOpaque(true);

        btnCreateWarrior.setText("Create ");
        btnCreateWarrior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWarriorActionPerformed(evt);
            }
        });

        btnAssignWeapon.setText("Assign weapon");
        btnAssignWeapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignWeaponActionPerformed(evt);
            }
        });

        btnReady.setText("READY");
        btnReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadyActionPerformed(evt);
            }
        });

        btnClearWeapons.setText("Clear table");
        btnClearWeapons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearWeaponsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txfWeaponName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCreateWeapon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClearWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(823, 823, 823)
                        .addComponent(btnAssignWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfWarriorName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxWarriorType, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoadImage))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarriorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReady, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreateWarrior, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarriorImage, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txfWarriorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxWarriorType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoadImage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAssignWeapon)))
                .addGap(18, 18, 18)
                .addComponent(btnCreateWarrior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfWeaponName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreateWeapon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClearWeapons)
                        .addGap(11, 11, 11)
                        .addComponent(btnReady, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadImageActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("*.Images", "jpg" , "gif" , "png");
        fileChooser.addChoosableFileFilter(extensionFilter);
        int result = fileChooser.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            
            lastImageUsedPath = filePath;
            
            ImageIcon imageIcon = new ImageIcon(filePath);
            Image image = imageIcon.getImage();
            
            ImageIcon resizedImage = resizeImage(image);
            lblWarriorImage.setIcon(resizedImage);
        }
        
        else if (result == JFileChooser.CANCEL_OPTION){
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_btnLoadImageActionPerformed

    private void btnCreateWarriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWarriorActionPerformed
        // TODO add your handling code here:
        String warriorName = txfWarriorName.getText();
        CharacterType warriorType = CharacterType.getCharacterTypeValue(cmbxWarriorType.getSelectedItem().toString().toUpperCase());
        
        ImageIcon warriorIcon = (ImageIcon) lblWarriorImage.getIcon();
        Image warriorImage = warriorIcon.getImage();
        
        Character newCharacter = new Warrior(warriorName, warriorType , lastImageUsedPath  , 100); //FIXME
        ((Warrior)newCharacter).setCharacterImage(warriorImage);
        addWarrior(newCharacter);
        txfWarriorName.setText("");
        
    }//GEN-LAST:event_btnCreateWarriorActionPerformed

    private void btnCreateWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWeaponActionPerformed
        // TODO add your handling code here:
        String weaponName = txfWeaponName.getText();
        System.out.println("Got: " + weaponName);
        Weapon newWeapon = new WarriorWeapon(weaponName , "DUMMY_STRING"); // FIXME
        this.addWeapon(newWeapon);
        txfWeaponName.setText("");
    }//GEN-LAST:event_btnCreateWeaponActionPerformed

    private void btnAssignWeaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignWeaponActionPerformed
        // TODO add your handling code here:
        int weaponIndex = tblWeapons.getSelectedRow();
        int warriorIndex = tblWarriors.getSelectedRow();
        
        if (warriorIndex == -1){
            JOptionPane.showMessageDialog(null, "No warrior selected", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if (weaponIndex == -1){
                JOptionPane.showMessageDialog(null, "Please select a weapon", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Weapon selectedWeapon = createdWeapons.get(weaponIndex);
                Warrior selectedWarrior = (Warrior) createdWarriors.get(warriorIndex);
                this.addWeaponToWarrior(selectedWarrior, warriorIndex, selectedWeapon);
            }
        }
        
    }//GEN-LAST:event_btnAssignWeaponActionPerformed

    private void btnClearWeaponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearWeaponsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) tblWeapons.getModel();
        tableModel.setRowCount(0);
        createdWeapons.clear();
                
    }//GEN-LAST:event_btnClearWeaponsActionPerformed

    private void btnReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadyActionPerformed
        // TODO add your handling code here:
        PlayerClient player = new PlayerClient("localhost", 1234, username , createdWarriors);
        player.run();
        
        GameWindow gameWindow = new GameWindow();
        gameWindow.setVisible(true);
        
        GameWindowController gmc = new GameWindowController(gameWindow, player);
        
        
        this.setVisible(false);
    }//GEN-LAST:event_btnReadyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignWeapon;
    private javax.swing.JButton btnClearWeapons;
    private javax.swing.JButton btnCreateWarrior;
    private javax.swing.JButton btnCreateWeapon;
    private javax.swing.JButton btnLoadImage;
    private javax.swing.JButton btnReady;
    private javax.swing.JComboBox<String> cmbxWarriorType;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblWarriorImage;
    private javax.swing.JTable tblWarriors;
    private javax.swing.JTable tblWeapons;
    private javax.swing.JTextField txfWarriorName;
    private javax.swing.JTextField txfWeaponName;
    // End of variables declaration//GEN-END:variables
}
